---
title: "O'Neil Quinn"
subtitle: "Research Opportunity Summary for Nora Hessen"
author:
  - "Dr. Jacqueline Padilla-Gamiño"
  - "Sarah S.D. Tanja"
date: "`r format(Sys.time(), '%d %B, %Y')`"  
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r instructions}
# We are offering support for undergraduate student experiential learning opportunities. These experiences could include, but are not limited to, efforts focusing on field work in the Puget Sound Region. Awards will be in the amount of $1000 and will be distributed directly to the student no later than June 01, 2023. Funds could be used at their discretion to support experiential learning opportunities. To apply for funding, faculty should provide a brief summary of the research opportunity including the educational benefit for a student, as well as an explanation of why you feel a given student would be a great candidate for this award. The application should be no longer than two pages and uploaded as a PDF below
```

What is the research opportunity?

- Studying at Friday Harbor Labs as part of the Marine Botany course taught by Dr. Freshwater and Dr. Mumford


Why Nora would be a great candidate for this award...


